AllCops:
  # Exclude:
  #   - config/initializers/third_party.rb

Style/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/RedundantBegin:
  Enabled: false